export const techBadges = {
    "React": "https://img.shields.io/badge/React-61DAFB?logo=react&logoColor=000",
    "Next.js": "https://img.shields.io/badge/Next.js-000000?logo=nextdotjs&logoColor=fff",
    "TypeScript": "https://img.shields.io/badge/TypeScript-3178C6?logo=typescript&logoColor=fff",
    "JavaScript": "https://img.shields.io/badge/JavaScript-F7DF1E?logo=javascript&logoColor=000",
    "Node.js": "https://img.shields.io/badge/Node.js-339933?logo=nodedotjs&logoColor=fff",
    "Express": "https://img.shields.io/badge/Express-000000?logo=express&logoColor=fff",
    "Vite": "https://img.shields.io/badge/Vite-646CFF?logo=vite&logoColor=fff",
    "Webpack": "https://img.shields.io/badge/Webpack-8DD6F9?logo=webpack&logoColor=000",
    "Babel": "https://img.shields.io/badge/Babel-F9DC3E?logo=babel&logoColor=000",
    "Parcel": "https://img.shields.io/badge/Parcel-000000?logo=parcel&logoColor=fff",
    "npm": "https://img.shields.io/badge/npm-CB3837?logo=npm&logoColor=fff",
    "Yarn": "https://img.shields.io/badge/Yarn-2C8EBB?logo=yarn&logoColor=fff",
    "pnpm": "https://img.shields.io/badge/pnpm-F69220?logo=pnpm&logoColor=000",
    "HTML": "https://img.shields.io/badge/HTML5-E34F26?logo=html5&logoColor=fff",
    "CSS": "https://img.shields.io/badge/CSS-639?logo=css&logoColor=fff",
    "Tailwind CSS": "https://img.shields.io/badge/Tailwind%20CSS-06B6D4?logo=tailwindcss&logoColor=fff",
    "Sass": "https://img.shields.io/badge/Sass-CC6699?logo=sass&logoColor=fff",
    "Styled Components": "https://img.shields.io/badge/styled--components-DB7093?logo=styledcomponents&logoColor=fff",
    "Redux": "https://img.shields.io/badge/Redux-764ABC?logo=redux&logoColor=fff",
    "React Router": "https://img.shields.io/badge/React%20Router-CA4245?logo=reactrouter&logoColor=fff",
    "Jest": "https://img.shields.io/badge/Jest-C21325?logo=jest&logoColor=fff",
    "Vitest": "https://img.shields.io/badge/Vitest-6E9F18?logo=vitest&logoColor=fff",
    "Cypress": "https://img.shields.io/badge/Cypress-17202C?logo=cypress&logoColor=fff",
    "Playwright": "https://img.shields.io/badge/Playwright-2EAD33?logo=playwright&logoColor=fff",
    "ESLint": "https://img.shields.io/badge/ESLint-4B32C3?logo=eslint&logoColor=fff",
    "Prettier": "https://img.shields.io/badge/Prettier-F7B93E?logo=prettier&logoColor=000",
    "Storybook": "https://img.shields.io/badge/Storybook-FF4785?logo=storybook&logoColor=fff",
    "GraphQL": "https://img.shields.io/badge/GraphQL-E10098?logo=graphql&logoColor=fff",
    "Apollo": "https://img.shields.io/badge/Apollo-311C87?logo=apollographql&logoColor=fff",
    "REST": "https://img.shields.io/badge/REST-1F1F1F?logo=swagger&logoColor=fff",
    "tRPC": "https://img.shields.io/badge/tRPC-398CCB?logo=trpc&logoColor=fff",
    "MobX": "https://img.shields.io/badge/MobX-EA6618?logo=mobx&logoColor=fff",

    "MongoDB": "https://img.shields.io/badge/MongoDB-47A248?logo=mongodb&logoColor=fff",
    "Mongoose": "https://img.shields.io/badge/Mongoose-880000?logo=mongoose&logoColor=fff",
    "PostgreSQL": "https://img.shields.io/badge/PostgreSQL-4169E1?logo=postgresql&logoColor=fff",
    "MySQL": "https://img.shields.io/badge/MySQL-4479A1?logo=mysql&logoColor=fff",
    "SQLite": "https://img.shields.io/badge/SQLite-003B57?logo=sqlite&logoColor=fff",
    "Prisma": "https://img.shields.io/badge/Prisma-2D3748?logo=prisma&logoColor=fff",
    "Firebase": "https://img.shields.io/badge/Firebase-FFCA28?logo=firebase&logoColor=000",
    "Supabase": "https://img.shields.io/badge/Supabase-3ECF8E?logo=supabase&logoColor=000",
    "Redis": "https://img.shields.io/badge/Redis-DC382D?logo=redis&logoColor=fff",
    "Elasticsearch": "https://img.shields.io/badge/Elasticsearch-005571?logo=elasticsearch&logoColor=fff",

    "Docker": "https://img.shields.io/badge/Docker-2496ED?logo=docker&logoColor=fff",
    "Kubernetes": "https://img.shields.io/badge/Kubernetes-326CE5?logo=kubernetes&logoColor=fff",
    "Nginx": "https://img.shields.io/badge/Nginx-009639?logo=nginx&logoColor=fff",
    "Apache": "https://img.shields.io/badge/Apache-D22128?logo=apache&logoColor=fff",
    "Git": "https://img.shields.io/badge/Git-F05032?logo=git&logoColor=fff",
    "GitHub": "https://img.shields.io/badge/GitHub-181717?logo=github&logoColor=fff",
    "GitLab": "https://img.shields.io/badge/GitLab-FC6D26?logo=gitlab&logoColor=fff",
    "Bitbucket": "https://img.shields.io/badge/Bitbucket-0052CC?logo=bitbucket&logoColor=fff",
    "Jenkins": "https://img.shields.io/badge/Jenkins-D24939?logo=jenkins&logoColor=fff",
    "GitHub Actions": "https://img.shields.io/badge/GitHub%20Actions-2088FF?logo=githubactions&logoColor=fff",
    "CircleCI": "https://img.shields.io/badge/CircleCI-343434?logo=circleci&logoColor=fff",

    "AWS": "https://img.shields.io/badge/AWS-232F3E?logo=amazonaws&logoColor=fff",
    "GCP": "https://img.shields.io/badge/Google%20Cloud-4285F4?logo=googlecloud&logoColor=fff",
    "Azure": "https://img.shields.io/badge/Azure-0078D4?logo=microsoftazure&logoColor=fff",
    "Vercel": "https://img.shields.io/badge/Vercel-000000?logo=vercel&logoColor=fff",
    "Netlify": "https://img.shields.io/badge/Netlify-00C7B7?logo=netlify&logoColor=fff",
    "Render": "https://img.shields.io/badge/Render-46E3B7?logo=render&logoColor=000",
    "Railway": "https://img.shields.io/badge/Railway-0B0D0E?logo=railway&logoColor=fff",
    "Fly.io": "https://img.shields.io/badge/Fly.io-000000?logo=flydotio&logoColor=fff",
    "Heroku": "https://img.shields.io/badge/Heroku-430098?logo=heroku&logoColor=fff",

    "Python": "https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=fff",
    "Django": "https://img.shields.io/badge/Django-092E20?logo=django&logoColor=fff",
    "Flask": "https://img.shields.io/badge/Flask-000000?logo=flask&logoColor=fff",
    "FastAPI": "https://img.shields.io/badge/FastAPI-009688?logo=fastapi&logoColor=fff",

    "Java": "https://img.shields.io/badge/Java-007396?logo=openjdk&logoColor=fff",
    "Spring Boot": "https://img.shields.io/badge/Spring%20Boot-6DB33F?logo=springboot&logoColor=fff",
    "Kotlin": "https://img.shields.io/badge/Kotlin-7F52FF?logo=kotlin&logoColor=fff",

    "Go": "https://img.shields.io/badge/Go-00ADD8?logo=go&logoColor=fff",
    "Rust": "https://img.shields.io/badge/Rust-000000?logo=rust&logoColor=fff",
    "C": "https://img.shields.io/badge/C-A8B9CC?logo=c&logoColor=000",
    "C++": "https://img.shields.io/badge/C%2B%2B-00599C?logo=c%2B%2B&logoColor=fff",

    "Android": "https://img.shields.io/badge/Android-3DDC84?logo=android&logoColor=fff",
    "Swift": "https://img.shields.io/badge/Swift-FA7343?logo=swift&logoColor=fff",
    "SwiftUI": "https://img.shields.io/badge/SwiftUI-0A84FF?logo=swift&logoColor=fff",
    "Xcode": "https://img.shields.io/badge/Xcode-147EFB?logo=xcode&logoColor=fff",

    "Flutter": "https://img.shields.io/badge/Flutter-02569B?logo=flutter&logoColor=fff",
    "Dart": "https://img.shields.io/badge/Dart-0175C2?logo=dart&logoColor=fff",
    "React Native": "https://img.shields.io/badge/React%20Native-61DAFB?logo=react&logoColor=000",
    "Expo": "https://img.shields.io/badge/Expo-000020?logo=expo&logoColor=fff",

    "Stripe": "https://img.shields.io/badge/Stripe-635BFF?logo=stripe&logoColor=fff",
    "Auth0": "https://img.shields.io/badge/Auth0-EB5424?logo=auth0&logoColor=fff",
    "Clerk": "https://img.shields.io/badge/Clerk-4B6BFB?logo=clerk&logoColor=fff",

    "Kafka": "https://img.shields.io/badge/Apache%20Kafka-231F20?logo=apachekafka&logoColor=fff",
    "RabbitMQ": "https://img.shields.io/badge/RabbitMQ-FF6600?logo=rabbitmq&logoColor=fff",
    "gRPC": "https://img.shields.io/badge/gRPC-5EC792?logo=grpc&logoColor=000",

    "Linux": "https://img.shields.io/badge/Linux-FCC624?logo=linux&logoColor=000",
    "Ubuntu": "https://img.shields.io/badge/Ubuntu-E95420?logo=ubuntu&logoColor=fff",
    "Alpine": "https://img.shields.io/badge/Alpine-0D597F?logo=alpinelinux&logoColor=fff",

    "Terraform": "https://img.shields.io/badge/Terraform-844FBA?logo=terraform&logoColor=fff",
    "Ansible": "https://img.shields.io/badge/Ansible-EE0000?logo=ansible&logoColor=fff",
    "Pulumi": "https://img.shields.io/badge/Pulumi-8A3391?logo=pulumi&logoColor=fff",

    "OpenAI": "https://img.shields.io/badge/OpenAI-412991?logo=openai&logoColor=fff",
    "Claude": "https://img.shields.io/badge/Claude-D97757?logo=claude&logoColor=fff",
    "Hugging Face": "https://img.shields.io/badge/Hugging%20Face-FFCC00?logo=huggingface&logoColor=000"
};